version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URI=sqlite:////app/instance/users.sqlite3  # Путь к базе данных
      - ADMIN=${ADMIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FLAG=practice{you_are_the_real_admin}  # Флаг задаётся здесь
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
      - db_data:/app/instance  # Том для хранения базы данных

volumes:
  db_data:  # Определяем том для базы данных